config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :products do
    resources :reviews, except: [:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  scope :three_most_recent, -> { order(created_at: :desc).limit(10)}

  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
end

app/models/products.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :author, presence: true

  validates :product_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end  end

    def edit
      @product = Product.find(params[:id])
      render :edit
    end

    def show
      @product = Product.find(params[:id])
      render :show
    end

    def update
      @product= Product.find(params[:id])
      if @product.update(product_params)
        redirect_to products_path
      else
        render :edit
      end
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_path
    end

    private
    def product_params
      params.require(:product).permit(:name, :genre)
    end

  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
  @product = Product.find(params[:product_id])
  @review = @product.reviews.new(review_params)
  if @review.save
    redirect_to product_path(@product)
  else
    render :new
  end
end

def show
  @product = Product.find(params[:product_id])
  @review = Review.find(params[:id])
  render :show
end

def edit
  @product = Product.find(params[:product_id])
  @review = Review.find(params[:id])
  render :edit
end

def update
  @review = Review.find(params[:id])
  if @review.update(review_params)
    redirect_to product_path(@review.product)
  else
    render :edit
  end
end

def destroy
  @review = Review.find(params[:id])
  @review.destroy
  redirect_to product_path(@review.product)
end


private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>

  <%= f.submit  %>
<% end %>

app/views/products/index.html.erb
<h1>Marios fine foods</h1>
<h2>Foods of the world, shipped fresh</h2>

<% if @products.any? %>
<ul>
  <% @products.each do |product| %>
  <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>
<% else %>
<p>There are no products yet.</p>
<% end %>



<p><%= link_to "Create new product", new_product_path %></p>

app/views/products/new.html.erb
<h1>New product</h1>

<% if @product.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @product do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :cost %>
<%= f.text_field :cost %>
<%= f.label :country_of_origin %>
<%= f.text_field :country_of_origin %>
  <%= f.submit  %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>


<% if @product.reviews.any? %>
<h4>Here are the reviews for this product:</h4>

<% @product.reviews.each do |review| %>
<ul>
  <li>
    <%= link_to review.author, product_review_path(@product, review) %>
  </li>
</ul>
<% end %>
<% else %>
<p>No reviews are listed for this product.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete product", product_path(@product),
  :data => {:confirm => "Are you sure?",
  :method => "delete"} %></p>

  <p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit review:</h1>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_area :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a new review:</h1>

<% if @review.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_area :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviewer: <%= @review.author %></h1>
<h2>Product: <%= @product.name %></h2>
<h2><%=@review.content_body%></h2>


<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
  :data => {:confirm => "Are you sure?",
  :method => "delete"} %></p>

  <p><%= link_to "Return to product", product_path(@product) %></p>

app/views/songs/edit.html.erb
<h1>Edit review:</h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_area :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/songs/show.html.erb
<h1>Review: <%= @review.name %></h1>
<h2>Product: <%= @product.name %></h2>


<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
  :data => {:confirm => "Are you sure?",
  :method => "delete"} %></p>

  <p><%= link_to "Return to product", product_path(@product) %></p>